### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#12]
First time trying the dashboard.

I have a small python file which looks as follows

```
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from explainerdashboard import RegressionExplainer, ExplainerDashboard

X_train = pd.read_pickle("X_train.pkl")
X_test = pd.read_pickle("X_test.pkl")
y_train = pd.read_pickle("y_train.pkl")
y_test = pd.read_pickle("y_test.pkl")

model = RandomForestRegressor(n_jobs=-1, random_state=42)

model = model.fit(X_train, y_train)

explainer = RegressionExplainer(model, X_test, y_test, shap="tree")
ExplainerDashboard(explainer).run()
```

Also i'm on windows and installed explainerdashboard using
```
conda create -n test_env python=3.8
conda activate test_env
pip install explainerdashboard
```

When running the code I get

```
(test_env) C:\Users\131416\python\modelling>python explainer_dashboard.py
Generating self.shap_explainer = shap.TreeExplainer(model)
Changing class type to RandomForestRegressionExplainer...
Building ExplainerDashboard..
Generating ShadowDecTree for each individual decision tree...
Generating layout...
Calculating shap values...
Calculating predictions...
Calculating residuals...
Calculating absolute residuals...
Calculating dependencies...
Calculating importances...
Calculating shap interaction values...
Registering callbacks...
Starting ExplainerDashboard on http://localhost:8050
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "explainerdashboard.dashboards" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\dash\dash.py", line 1093, in _setup_server
    _validate.validate_layout(self.layout, self._layout_value())
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\dash\_validate.py", line 348, in validate_layout
    raise exceptions.DuplicateIdError(
dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `whatif-SL-input-qHjwzsAtGC`
127.0.0.1 - - [11/Nov/2020 07:48:30] "GET / HTTP/1.1" 500 -
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\flask\app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\dash\dash.py", line 1093, in _setup_server
    _validate.validate_layout(self.layout, self._layout_value())
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\dash\_validate.py", line 348, in validate_layout
    raise exceptions.DuplicateIdError(
dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `whatif-SL-input-qHjwzsAtGC`
127.0.0.1 - - [11/Nov/2020 07:48:30] "GET /favicon.ico HTTP/1.1" 500 -
```

**Comment by raybellwaves** [comment]
Worked fine with 

`ExplainerDashboard(explainer, whatif=False).run()`

**Comment by oegedijk** [comment]
Hmm, that is really strange. Especially as the code is basically equivalent to the test code (that is passing on python 3.6, 3.7, 3.8, linux, windows and mac), or that is running here: [http://titanicexplainer.herokuapp.com/regression/](http://titanicexplainer.herokuapp.com/regression/)

To explain the error: every dash element should have a unique id. But from the error it seems that the whatif component/tab got included twice in the layout somehow, leading to duplicate id's? But I can't see how that would be possible.

**Comment by oegedijk** [comment]
Ah, wait, I think I got it: Do you have duplicate feature names somehow? 

The whatif tab has an input for each feature. But it seems that the input for feature "SL" gets included twice.

**Comment by raybellwaves** [comment]
Thanks. Will check

**Comment by raybellwaves** [comment]
>  input for feature "SL" gets included twice.

Correct. Thanks.
