### ISSUE TITLE
Unable to deactivate the additivity_check

### ISSUE THREAD

**Issue by Simon-Free** [oegedijk/explainerdashboard#143]
Versions : shap 0.39, python 3.6.8, explainerdashboard 0.3.6.2

Hello ! I'm trying to build an usual dashboard, something like: 
```python
X_test = my_X_data()
y_test = my_y_data()
model = my_xgboost_model()
model["XGB"].best_estimator_.get_booster().feature_names = features_name
explainer = RegressionExplainer(Pipeline([('imputer', model["imputer"]), ("XGB", model["XGB"].best_estimator_)]),
                                X_test, y_test, precision="float32", shap="tree")
dashboard = ExplainerDashboard(explainer, shap_interaction=False, index_dropdown=False)
```

I get the following error: 

```python
Traceback (most recent call last):
  File "C:\Users\***\Bureau\repo_prog\forecast\src\entity\mlflow_output\recording.py", line 156, in generate_explainer_dashboard
    dashboard = ExplainerDashboard(explainer, shap_interaction=False, index_dropdown=False)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboards.py", line 587, in __init__
    fluid=fluid))
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboards.py", line 90, in __init__
    self.tabs  = [instantiate_component(tab, explainer, name=str(i+1), **kwargs) for i, tab in enumerate(tabs)]
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboards.py", line 90, in <listcomp>
    self.tabs  = [instantiate_component(tab, explainer, name=str(i+1), **kwargs) for i, tab in enumerate(tabs)]
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboard_methods.py", line 688, in instantiate_component
    component = component(explainer, name=name, **kwargs)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboard_components\composites.py", line 251, in __init__
    logs=logs, **kwargs)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\dashboard_components\regression_components.py", line 938, in __init__
    self.col = self.explainer.columns_ranked_by_shap()[0]
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 1043, in columns_ranked_by_shap
    return self.mean_abs_shap_df(pos_label).Feature.tolist()
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 1025, in mean_abs_shap_df
    self._mean_abs_shap_df = (self.get_shap_values_df(pos_label)[self.merged_cols].abs().mean()
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\explainerdashboard\explainers.py", line 959, in get_shap_values_df
    self._shap_values_df = pd.DataFrame(self.shap_explainer.shap_values(self.X),
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\shap\explainers\_tree.py", line 376, in shap_values
    self.assert_additivity(out, model_output_vals)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\shap\explainers\_tree.py", line 539, in assert_additivity
    check_sum(self.expected_value + phi.sum(-1), model_output)
  File "C:\Users\***\AppData\Local\pypoetry\Cache\virtualenvs\forecast-T9U7-MYL-py3.6\lib\site-packages\shap\explainers\_tree.py", line 533, in check_sum
    raise Exception(err_msg)
Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was -105.507812, while the model output was -105.539818. If this difference is acceptable you can set check_additivity=False to disable this check.
```

Since the difference is acceptable to me, I set `check_additivity=False`, but I get the same error. Diving deeper into the code, I do think that the argument is not repercuted to the "shap_values" method.

**Comment by oegedijk** [comment]
Hi @Simon-Free,

Apologies for late reply, newborn and work keeping me busy :) 

And you are right, the check_additivity option is not forwarded to the shap explainer. Will see if I can add it.

Otherwise, in any case I'm planning a feature for the next release to load pre-calculated shap values, so that way you could add the flag manually, and then add those values to the explainer...

**Comment by oegedijk** [comment]
so you can add shap values manually now with the `explainer.set_shap_values()` method...
