### ISSUE TITLE
Temporary failure in name resolution - linux

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#18]
Tested on my linux machine

Installation:

```
$ conda create -n test_env python=3.8
$ conda activate test_env
$ pip install explainerdashboard
```

and tested this https://explainerdashboard.readthedocs.io/en/latest/index.html#a-more-extended-example

This may be outside of explainerdashboard

```
>>> from sklearn.ensemble import RandomForestClassifier
>>> 
>>> from explainerdashboard import ClassifierExplainer, ExplainerDashboard
>>> from explainerdashboard.datasets import titanic_survive
>>> 
>>> X_train, y_train, X_test, y_test = titanic_survive()
>>> 
>>> model = RandomForestClassifier(n_estimators=50, max_depth=5)
>>> model.fit(X_train, y_train)
RandomForestClassifier(max_depth=5, n_estimators=50)
>>> 
>>> explainer = ClassifierExplainer(
...                 model, X_test, y_test,
...                 # optional:
...                 cats=['Sex', 'Deck', 'Embarked'],
...                 labels=['Not survived', 'Survived'])
Note: shap=='guess' so guessing for RandomForestClassifier shap='tree'...
Note: model_output=='probability', so assuming that raw shap output of RandomForestClassifier is in probability space...
Generating self.shap_explainer = shap.TreeExplainer(model)
Detected RandomForestClassifier model: Changing class type to RandomForestClassifierExplainer...
>>> 
>>> db = ExplainerDashboard(explainer, title="Titanic Explainer",
...                     whatif=False, # you can switch off tabs with bools
...                     shap_interaction=False,
...                     decision_trees=False)
Building ExplainerDashboard..
Generating layout...
Calculating shap values...
Calculating dependencies...
Calculating permutation importances (if slow, try setting n_jobs parameter)...
Calculating categorical permutation importances (if slow, try setting n_jobs parameter)...
Calculating prediction probabilities...
Calculating predictions...
Calculating pred_percentiles...
Registering callbacks...
>>> db.run(port=8051)
Starting ExplainerDashboard on http://localhost:8051
Dash is running on http://x86_64-conda_cos6-linux-gnu:8051/

 * Serving Flask app "explainerdashboard.dashboards" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/explainerdashboard/dashboards.py", line 674, in run
    self.app.run_server(port=port, **kwargs)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/dash/dash.py", line 1716, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by oegedijk** [comment]
Looks like the port was already occupied?

**Comment by oegedijk** [comment]
Did you figure out what went wrong here?

**Comment by raybellwaves** [comment]
Thanks for the prompt. I'll check again on my linux soon.

**Comment by raybellwaves** [comment]
Still persists.

Simplified a bit and did `db.run()` to use default port (8050).

I see

```
Starting ExplainerDashboard on http://localhost:8050
Dash is running on http://x86_64-conda_cos6-linux-gnu:8050/
```

On my windows I see

```
```

**Comment by oegedijk** [comment]
Yeah, it seems that localhost is `x86_64-conda_cos6-linux-gnu` on your linux machine and that this may somehow prevent dash from starting?

What happens if you try a simple dash dashboard (from https://dash.plotly.com/layout):

```
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by raybellwaves** [comment]
Closing in favor of https://github.com/plotly/dash/issues/1480
