### ISSUE TITLE
The Permutation was generated with a version of explainerdashboard<0.3 and therefore not compatible with this version

### ISSUE THREAD

**Issue by mirix** [oegedijk/explainerdashboard#227]
Hello,

I do not understand the following error message:

> Building ExplainerDashboard..
> Traceback (most recent call last):
>   File "/home/mirix/work/loans/shap/test_explainerdb.py", line 146, in <module>
>     db = ExplainerDashboard(explainer, 'Loan Eligibility',
>   File "/home/mirix/.local/lib/python3.10/site-packages/explainerdashboard/dashboards.py", line 474, in __init__
>     raise ValueError(f"The {explainer.__class__.__name__} was generated "
> ValueError: The Permutation was generated with a version of explainerdashboard<0.3 and therefore not compatible with this version of ExplainerDashboard due to breaking changes in between major versions! Please rebuild your Permutation with this version, or downgrade back to explainerdashboard==0.2.20.1!

But both my packages seem to be current:

explainerdashboard==0.4.0

shap==0.41.0

I am using the following code:

```
best_model = tune_search.best_estimator_.fit(X_train_scaled, y_train)

explainer = shap.Explainer(best_model.predict, X_test)
shap_values = explainer(X_test)

from explainerdashboard.explainers import *
from explainerdashboard.dashboards import *
from explainerdashboard.datasets import *

db = ExplainerDashboard(explainer, 'Loan Eligibility',
                        model_summary=True,  
                        contributions=True,
                        shap_dependence=True,
                        shap_interaction=False, # switch off individual tabs
                        decision_trees=True)
db.run(port=8051)
```

Should I downgrade as suggested or is there another solution?

**Comment by mirix** [comment]
If I downgrade I get this:

The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

> The dash_table package is deprecated. Please replace
> `import dash_table` with `from dash import dash_table`
> 
> Also, if you're using any of the table format helpers (e.g. Group), replace 
> `from dash_table.Format import Group` with 
> `from dash.dash_table.Format import Group`
> Building ExplainerDashboard..
> Traceback (most recent call last):
>   File "/home/mirix/work/loans/shap/test_explainerdb.py", line 146, in <module>
>     db = ExplainerDashboard(explainer, 'Loan Eligibility',
>   File "/home/mirix/.local/lib/python3.10/site-packages/explainerdashboard/dashboards.py", line 399, in __init__
>     self.explainer.onehot_dict = self.explainer.cats_dict
> AttributeError: 'Permutation' object has no attribute 'cats_dict'

**Comment by mirix** [comment]
OK, this works:
```

best_model = tune_search.best_estimator_.fit(X_train_scaled, y_train)

from explainerdashboard import ClassifierExplainer, ExplainerDashboard

explainer = ClassifierExplainer(best_model[0], X_test, y_test)
ExplainerDashboard(explainer).run()
```
