### ISSUE TITLE
[Bug] Import fails with new flask 

### ISSUE THREAD

**Issue by tvdboom** [oegedijk/explainerdashboard#259]
After updating flask to the newest version 2.3.1, importing `explainerdashboard` raises this error:

```
Traceback (most recent call last):
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4c1ffb59aabf>", line 1, in <module>
    import explainerdashboard
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\explainerdashboard\__init__.py", line 5, in <module>
    from .dashboards import ExplainerDashboard, ExplainerHub, InlineExplainer
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\explainerdashboard\dashboards.py", line 41, in <module>
    from flask_simplelogin import SimpleLogin, login_required
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\flask_simplelogin\__init__.py", line 24, in <module>
    from flask_wtf import FlaskForm
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\flask_wtf\__init__.py", line 3, in <module>
    from .recaptcha import *
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\flask_wtf\recaptcha\__init__.py", line 2, in <module>
    from .fields import *
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\flask_wtf\recaptcha\fields.py", line 3, in <module>
    from . import widgets
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\flask_wtf\recaptcha\widgets.py", line 4, in <module>
    JSONEncoder = json.JSONEncoder
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

**Comment by shivsn** [comment]
Downgrade your flask version to **2.2.3**  it solves the error.

**Comment by tvdboom** [comment]
Yes, that works indeed. But it would be nice if  @oegedijk could release a new version with either a fix in the code or a version restriction to not make other libs that are dependend on this one fail.

**Comment by oegedijk** [comment]
@tvdboom currently on holiday, will see what I can do. Seems that Flask is releasing breaking changes in minor versions. Received an email from dash that they are considering just pinning flask to a known working version as well.

**Comment by oegedijk** [comment]
Had a little bit of time to investigate, and seems the issue is in flask_simplelogin that had pinned the major version of flask-wtf. Opened an issue https://github.com/flask-extensions/Flask-SimpleLogin/issues/33 and submitted a pull request https://github.com/flask-extensions/Flask-SimpleLogin/pull/34

Not sure how actively that library is still maintained though, so in the meantime will probably have to come up with a fix of our own...

**Comment by tvdboom** [comment]
Awesome! Let's hope they merge and rrlease soon then

**Comment by oegedijk** [comment]
just released a version with some pinned dependencies also with numpy<1.24 and pandas <2.0. Should work now. Shap needs to stop using np.bool for example which used to give a warning but now gives an error...
