### ISSUE TITLE
Plot vs. feature empty

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#28]
(Tab "model_summary" in vanilla dashboard)
I'm using a non-special self-made dataset so I'm not sure why it's broken. Here is the error:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "c:\users\...\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\...\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\...\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\...\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\...\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\...\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\...\venv\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "c:\...\venv\lib\site-packages\dash\dash.py", line 1007, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "c:\...\venv\lib\site-packages\explainerdashboard\dashboard_components\regression_components.py", line 370, in update_residuals_graph
    winsor=winsor, dropna=True)
  File "c:\users\...\venv\lib\site-packages\explainerdashboard\explainers.py", line 2551, in plot_residuals_vs_feature
    self.y[na_mask], self.preds[na_mask], col_vals[na_mask],
  File "c:\users\...\venv\lib\site-packages\pandas\core\series.py", line 902, in __getitem__
    key = check_bool_indexer(self.index, key)
  File "c:\users\...\venv\lib\site-packages\pandas\core\indexing.py", line 2183, in check_bool_indexer
    "Unalignable boolean Series provided as "
pandas.core.indexing.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
```

**Comment by oegedijk** [comment]
Do you have the code that generated this error? 

Just added the plot vs feature component in the latest release so could be that there are still bugs...

**Comment by hkoppen** [comment]
```
explainer = RegressionExplainer(pipe.dec_tree, X, y)

ExplainerDashboard(explainer,
                   importances=True,
                   model_summary=True,
                   contributions=True,
                   whatif=True,
                   shap_dependence=True,
                   shap_interaction=False, # Can be quite slow
                   decision_trees=False, # Not applicable for a single tree, usable for forest or xgboost
                   
    ).run()
```

where X is an dataframe of shape (1000, 37) and y a series with according target values.

**Comment by oegedijk** [comment]
Hmm, without seeing the data on which it breaks it is a little bit hard to debug, so could you try a few things?

1. Does it work with the built-in titanic datasets from the examples? If not it's something about your system, if it does then there's probably something different about your dataset.
2. Could you check that the indexes for the X and y match? (they should automatically be made to match, but good to check)
    ```python
    assert np.all(explainer.X.index == explainer.y.index)
    ```
3. Do you get the same bug when you run
    ```python
    explainer.plot_residuals_vs_feature("Age")
    ```
    ?

4.  In case it still fails, could you try monkeypatching this fix and see if it helps?
```python
import types
from explainerdashboard.explainer_plots import plotly_residuals_vs_col

def plot_residuals_vs_feature2(self, col, residuals='difference', round=2, 
                dropna=True, points=True, winsor=0):
        """Plot residuals vs individual features

        Args:
          col(str): Plot against feature col
          residuals (str, {'difference', 'ratio', 'log-ratio'} optional): 
                    How to calcualte residuals. Defaults to 'difference'.
          round(int, optional): rounding to perform on residuals, defaults to 2
          dropna(bool, optional): drop missing values from plot, defaults to True.
          points (bool, optional): display point cloud next to violin plot. 
                    Defaults to True.
          winsor (int, 0-50, optional): percentage of outliers to winsor out of 
                    the y-axis. Defaults to 0.

        Returns:
          plotly fig
        """
        if self.y_missing:
            raise ValueError("No y was passed to explainer, so cannot plot residuals!")
        assert col in self.columns or col in self.columns_cats, \
            f'{col} not in columns or columns_cats!'
        col_vals = self.X_cats[col] if self.check_cats(col) else self.X[col]
        na_mask = col_vals != self.na_fill if dropna else pd.Series(np.array([True]*len(col_vals)), index=self.X.index) 
        return plotly_residuals_vs_col(
            self.y[na_mask], self.preds[na_mask], col_vals[na_mask], 
            residuals=residuals, idxs=self.idxs.values[na_mask], points=points, 
            round=round, winsor=winsor, index_name=self.index_name)
    
explainer.plot_residuals_vs_feature2 = types.MethodType(plot_residuals_vs_feature2, explainer)
explainer.plot_residuals_vs_feature2("Age")
```

**Comment by oegedijk** [comment]
Wait! Found it! The bug is with dataframes that have a RangeIndex. (the test datasets all have str indexes, so bug didn't show up in the tests).

For now here's the patch:

```
X.index = X.index.astype(str)
explainer = RegressionExplainer(model, X, y)

ExplainerDashboard(explainer,
                   importances=True,
                   model_summary=True,
                   contributions=True,
                   whatif=True,
                   shap_dependence=True,
                   shap_interaction=False,
                   decision_trees=False
                   
    ).run()
```

Will release a new version soon that fixes this bug. 

Thanks for finding it and pointing it out!

**Comment by hkoppen** [comment]
Nice catch, works perfectly now!

**Comment by oegedijk** [comment]
released the bug fix, so if you `pip install -U explainerdashboard` then it should also work now without the patch.
