### ISSUE TITLE
Problem with deploying a custom dashboard using waitress

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#32]
I am currently trying to deploy explainer dashboards using waitress. Whereas it's working fine using the vanilla regression dashboard, there is an error when running _waitress-serve --call "dashboard:create_c_app"_ where dashboard.py is

```
from explainerdashboard import ExplainerDashboard
from custom_tabs import *

def create_c_app():
    db = ExplainerDashboard.from_config("dashboard.yaml")
    app = db.flask_server()
    return app
```

The error is

```
Traceback (most recent call last):
  File "C:\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\...\venv\Scripts\waitress-serve.exe\__main__.py", line 7, in <module>
  File "c:\...\venv\lib\site-packages\waitress\runner.py", line 280, in run
    app = app()
  File "C:\...\dashboard.py", line 10, in create_c_app
    db = ExplainerDashboard.from_config("dashboard.yaml")
  File "c:\...\venv\lib\site-packages\explainerdashboard\dashboards.py", line 483, in from_config
    tabs = cls._yamltabs_to_tabs(dashboard_params['tabs'], explainer)
  File "c:\...\venv\lib\site-packages\explainerdashboard\dashboards.py", line 611, in _yamltabs_to_tabs
    return [instantiate_tab(tab, explainer)  for tab in yamltabs]
  File "c:\...\venv\lib\site-packages\explainerdashboard\dashboards.py", line 611, in <listcomp>
    return [instantiate_tab(tab, explainer)  for tab in yamltabs]
  File "c:\...\venv\lib\site-packages\explainerdashboard\dashboards.py", line 600, in instantiate_tab
    tab_class = getattr(import_module(tab['module']), tab['name'])
AttributeError: module '__main__' has no attribute 'CustomDescriptiveTab
```

The .yaml file looks like this:
```
[...]
    decision_trees: true
    tabs:
    - name: CustomDescriptiveTab
      module: __main__
      params: null
    - name: CustomFeatImpTab
      module: __main__
      params: null
    - name: CustomWhatIfTab
      module: __main__
      params: null
```

I don't understand why running via waitress is not working whereas loading the dashboard using ExplainerDashboard.from_config("dashboard.yaml") and running it locally works fine.

**Comment by oegedijk** [comment]
I see that you import the custom tabs from the `custom_tabs` module. However it seems that when you generated the `dashboard.yaml` these were actually declared in `__main__`.

So you can either manually change the modules to `custom_tabs` in the `dashboard.yaml`, or generate the yaml something like this

```python
from explainerdashboard import ExplainerDashboard
from custom_tabs import *

explainer = ClassifierExplainer(...)
db = ExplainerDashboard(explainer, [CustomDescriptiveTab, CustomFeatImpTab, CustomWhatIfTab])
db.to_yaml("dashboard.yaml")
```

**Comment by hkoppen** [comment]
True! I did update the yaml-file, which is correctly reflecting the module now. However, I face another error now when running waitress-serve --port=8060 "dashboard:create_c_app":

```
Serving on http://...
ERROR:waitress:Exception while serving /
Traceback (most recent call last):
  File "c:\...\venv\lib\site-packages\waitress\channel.py", line 350, in service
    task.service()
  File "c:\...\venv\lib\site-packages\waitress\task.py", line 171, in service
    self.execute()
  File "c:\...\venv\lib\site-packages\waitress\task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
TypeError: create_c_app() takes 0 positional arguments but 2 were given
```

where dashboard.py is

```
from explainerdashboard import ExplainerDashboard
from custom_tabs import *
from waitress import serve


def create_c_app():
    db = ExplainerDashboard.from_config("dashboard.yaml")
    app = db.flask_server()
    return app

if __name__ == "__main__":
    serve(create_c_app(), host='0.0.0.0', port=8050)
```

Note that running python dashboard.py is working fine (which was the case even before i fixed the yaml-file!)

**Comment by oegedijk** [comment]
I have never used waitress, but would this work:

```python
from explainerdashboard import ExplainerDashboard
from custom_tabs import *
from waitress import serve


def create_c_app():
    db = ExplainerDashboard.from_config("dashboard.yaml")
    app = db.flask_server()
    return app

app = create_c_app()

if __name__ == "__main__":
    serve(app, host='0.0.0.0', port=8050)
```

And then from the command line:

```sh
waitress-serve --port=8080 dashboard:app
```

**Comment by hkoppen** [comment]
Yes, that's the way to go. Apparently I did follow other examples too blindly, thanks for your support! 

For future reference: it suffices to use 

```
from explainerdashboard import ExplainerDashboard

app = ExplainerDashboard.from_config("dashboard.yaml").flask_server()
```

and then run _waitress-serve --port=8070 dashboard:app_ in command line (using a suitable port).

**Comment by oegedijk** [comment]
Nice one-liner indeed :)

**Comment by oegedijk** [comment]
And thanks for pointing out `waitress` - seems like a cool library, will see if I can build it into explainerdashboard itself.
