### ISSUE TITLE
logins for hub requires list of lists

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#67]
Previously I raised #43 and it was included.

so you can do
```
db = ExplainerDashboard.from_config(
    "config/dashboard.yaml", logins=["oege", os.getenv("PW")]
)
```
Instead of `[["oege", os.getenv("PW")]]` if there is only one user.

However, this doesn't work with `ExplainerHub`

```
db1 = ExplainerDashboard.from_config(
    "config/dashboard1.yaml", logins=["oege", os.getenv("PW1")]
)
db2 = ExplainerDashboard.from_config(
    "config/dashboard2.yaml", logins=["ray", os.getenv("PW2")]
)
hub = ExplainerHub([db1, db2])
```

gives
```
Traceback (most recent call last):
  File "src/create_hub.py", line 11, in <module>
    hub = ExplainerHub([db1, db2])
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\explainerdashboard\dashboards.py", line 993, in __init__
    self.dashboards = self._instantiate_dashboards(dashboards, **kwargs)
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\explainerdashboard\dashboards.py", line 1185, in _instantiate_dashboards
    for user, password in dashboard.logins:
ValueError: too many values to unpack (expected 2)
```

**Comment by oegedijk** [comment]
Ah, I converted it to [["oege", "password"]], but didn't actually stored it to self.logins, which is why the ExplainerHub did not find it. Should be fixed in next release.

**Comment by oegedijk** [comment]
currently the logins of `ExplainerDashboard` do not get hashed though as they are stored to `.yaml` so be careful about storing them this way. Better to define them in `ExplainerHub`.
