### ISSUE TITLE
Issue with shap='deep' using tensorflow

### ISSUE THREAD

**Issue by aprimera** [oegedijk/explainerdashboard#73]
Hello,

I tried the following scenario using an ANN with the latest Tensorflow and the shap='deep (https://github.com/aprimera/explainerdashboard).

However I get the following error:

Traceback (most recent call last):
  File "explainer.py", line 92, in <module>
    shap='deep',
  File "C:\ProgramData\Anaconda3\lib\site-packages\explainerdashboard\explainers.py", line 1727, in __init__
    _ = self.shap_explainer
  File "C:\ProgramData\Anaconda3\lib\site-packages\explainerdashboard\explainers.py", line 1790, in shap_explainer
    self._shap_explainer = shap.DeepExplainer(self.model, self.X_background)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\_deep\__init__.py", line 84, in __init__
    self.explainer = TFDeep(model, data, session, learning_phase_flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 131, in __init__
    self.graph = _get_graph(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\tf_utils.py", line 46, in _get_graph
    return explainer.model_output.graph
AttributeError: 'KerasTensor' object has no attribute 'graph'

After downgrading tensorflow I am getting more errors:

Traceback (most recent call last):
  File "explainer.py", line 92, in <module>
    shap='deep',
  File "C:\ProgramData\Anaconda3\lib\site-packages\explainerdashboard\explainers.py", line 1727, in __init__
    _ = self.shap_explainer
  File "C:\ProgramData\Anaconda3\lib\site-packages\explainerdashboard\explainers.py", line 1790, in shap_explainer
    self._shap_explainer = shap.DeepExplainer(self.model, self.X_background)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\_deep\__init__.py", line 84, in __init__
    self.explainer = TFDeep(model, data, session, learning_phase_flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 158, in __init__
    self.expected_value = tf.reduce_mean(self.model(self.data), 0)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\sequential.py", line 372, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\functional.py", line 386, in call
    inputs, training=training, mask=mask)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\functional.py", line 508, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\layers\core.py", line 1198, in call
    dtype=self._compute_dtype_object)
  File "C:\Users\prime\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\layers\ops\core.py", line 45, in dense
    if inputs.dtype.base_dtype != dtype.base_dtype:
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'

Please do you have any idea what could be causing the issue or potential workarounds?

Thanks!

**Comment by oegedijk** [comment]
Can you get it to work with the `shap` library directly?

https://github.com/slundberg/shap#deep-learning-example-with-deepexplainer-tensorflowkeras-models

The error seems to be that `shap.DeepExplainer` expects a numpy array, but instead gets passed a numpy array. (guess that's a difference between shap.TreeExplainer, which does accept pd.dataframes)

So you could try passing the underlying numpy array in the background dataset directly: `explainer = ClassifierExplainer(model, X_test, y_test, X_background=X.head(100).values)`. Does that work?

Then I just have to make sure that ClassifierExplainer also passes on the numpy array instead of the full dataframe..

**Comment by oegedijk** [comment]
PyTorch NN models are now supported through skorch (https://github.com/skorch-dev/skorch/). 

tensorflow will probably not be supported for now, unless there is some nice tabular tensorflow library akin to skorch that I could use. 

Closing this for now.
