### ISSUE TITLE
Parameter summary_type in ShapSummaryComponent not working

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#77]
At least in v0.2.19.1 - setting `summary_type = 'aggregated'` yields the following error:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\...\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\...\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\...\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\...\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\...\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\...\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\...\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\...\lib\site-packages\dash\dash.py", line 1007, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\...\lib\site-packages\explainerdashboard\dashboard_components\shap_components.py", line 196, in update_shap_summary_graph
    return (plot, dash.no_update, dash.no_update)
UnboundLocalError: local variable 'plot' referenced before assignment
```

Is `hide_type = True` needed?

**Comment by oegedijk** [comment]
try `summary_type = 'aggregate'` :)

(will add an `assert summary_type in {'aggregate', 'detailed'}` to prevent typos like this...)
